### ISSUE TITLE
Can't create group or execute similar actions

### ISSUE THREAD

**Issue by tionis** [dmonn/socialize#8] opened 2017-01-27 23:32 UTC
I can't execute any actions apart from register, login and easter eggs, because it throws an Attribute Error: 'NoneType' object has no attribute 'status code'

**Comment by dmonn** [comment] 2017-01-29 21:31
Hey @tionis . Can you please give me some more information on the OS you use etc.? The error message seems like there was an error with the server. However it worked after my test now. Can you confirm that you still encounter this error?

**Comment by tionis** [comment] 2017-01-30 21:11
Sure 
I am using Windows 8.1 and the error still occurs ist seens to be an error in the Python script.

**Comment by dmonn** [comment] 2017-01-31 20:51
Hey, I still can't reproduce the error, I have tested it in my Windows 8.1 VM. Have you installed Socialize via pip? If so, which version are you using right now? Also, could you paste the full traceback in here? Thanks.

**Comment by tionis** [comment] 2017-01-31 21:37
I installed socialize via pip, it should be version 1.0.5.
This is the error:
C:\Windows\system32>socl find friends
An error occured. Send this to your administrator: name 'file' is not defined
Traceback (most recent call last):
  File "C:\Python34\Scripts\socl-script.py", line 9, in <module>
    load_entry_point('socialize==1.0.5', 'console_scripts', 'socl')()
  File "C:\Python34\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python34\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python34\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python34\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python34\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python34\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Python34\lib\site-packages\socialize\router.py", line 238, in friends

    finders.random_users()
  File "C:\Python34\lib\site-packages\socialize\services\finder_service.py", lin
e 8, in random_users
    self.format_user_list(r)
  File "C:\Python34\lib\site-packages\socialize\services\finder_service.py", lin
e 20, in format_user_list
    for user in u:
TypeError: 'NoneType' object is not iterable

**Comment by dmonn** [comment] 2017-02-01 08:37
Ok I will check that out. Is that always the case or just with this specific command?

**Comment by tionis** [comment] 2017-02-01 09:36
This error occurs everytime i execute an non-easteregg non-login command

Dominic Monn <notifications@github.com> schrieb am Mi., 1. Feb. 2017 09:37:

**Comment by dmonn** [comment] 2017-02-01 15:50
Problem was the `file()` function which was deprecated in Python3.5. It's fixed now with newly released version 1.0.6.

**Closed by dmonn** 2017-02-01 15:50 UTC
